// gcode-import.test.ts
// Run with:  npm run test:import
// (node --experimental-strip-types src/lib/gcode-import.test.ts)
//
// The file-reading and matching half of gcode import. Uses real File and zip
// objects (Node 22 has File globally; fflate builds the 3MF), so these run
// the same code path the browser does.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { strToU8, zipSync } from 'fflate';
import {
  HEAD_BYTES,
  TAIL_BYTES,
  condenseGcode,
  headTailText,
  readSlicedFile,
  titleFromFileName,
} from './gcode-file.ts';
import { parseGcode } from './gcodeParse.ts';
import { matchMachines, matchMaterial } from './import-match.ts';

const HEADER = '; generated by OrcaSlicer 2.2.0\n; total estimated time: 2h 14m 8s\n; filament used [g] = 45.34\n';
const CONFIG = '; CONFIG_BLOCK_START\n; nozzle_temperature = 245\n; filament_type = PETG\n; printer_model = Bambu Lab P1S\n; CONFIG_BLOCK_END\n';

// --------------------------------------------------------------------------
// condensing and slicing
// --------------------------------------------------------------------------

test('condense keeps comments and temperature commands, drops motion', () => {
  const out = condenseGcode('; a\nG1 X1 Y2 E0.1\nM104 S210\n  ; b\nM140 S60\nG28\nM109 S215\nM190 S60\n');
  assert.equal(out, '; a\nM104 S210\n; b\nM140 S60\nM109 S215\nM190 S60');
});

test('headTailText leaves small input untouched', () => {
  const s = 'line one\nline two\n';
  assert.equal(headTailText(strToU8(s)), s);
});

test('headTailText drops the partial line at each cut', () => {
  const s = 'AAAA\nBBBB\nCCCC\nDDDD\nEEEE\n';
  // head 7 bytes = "AAAA\nBB" -> keeps "AAAA\n"; tail 7 bytes = "D\nEEEE\n" -> keeps "EEEE\n"
  assert.equal(headTailText(strToU8(s), 7, 7), 'AAAA\nEEEE\n');
});

// --------------------------------------------------------------------------
// reading files
// --------------------------------------------------------------------------

test('plain gcode file reads and parses', async () => {
  const r = await readSlicedFile(new File([HEADER + 'G1 X1\n' + CONFIG], 'benchy.gcode'));
  assert.equal(r.ok, true);
  if (!r.ok) return;
  assert.equal(r.kind, 'gcode');
  const p = parseGcode(r.text);
  assert.equal(p.durationMinutes, 134.13);
  assert.equal(p.materialQtyUsedG, 45.34);
  assert.equal(p.printerModel, 'Bambu Lab P1S');
});

test('a large file: metadata at both ends survives, the middle is never read', async () => {
  const filler = 'G1 X10.000 Y10.000 E0.01000\n';
  const middle = filler.repeat(Math.ceil((HEAD_BYTES + TAIL_BYTES + 1024 * 1024) / filler.length));
  // A marker in the unread gap: past the head window, before the tail window.
  // The file is head + tail + 1 MB, so the gap is the 1 MB after HEAD_BYTES.
  const cut = middle.indexOf('\n', HEAD_BYTES + 512 * 1024) + 1;
  const mid = middle.slice(0, cut) + '; MIDDLE_MARKER\n' + middle.slice(cut);
  const file = new File([HEADER, mid, CONFIG], 'big.gcode');
  assert.ok(file.size > HEAD_BYTES + TAIL_BYTES, 'fixture must exceed head + tail');

  const r = await readSlicedFile(file);
  assert.equal(r.ok, true);
  if (!r.ok) return;
  assert.equal(r.text.includes('MIDDLE_MARKER'), false);
  const p = parseGcode(r.text);
  assert.equal(p.durationMinutes, 134.13, 'from the head');
  assert.equal(p.parameters.nozzle_temp, 245, 'from the tail');
  assert.equal(p.filamentType, 'PETG', 'from the tail');
});

test('Bambu .gcode.3mf: plate gcode is extracted, first plate wins, extra plates noted', async () => {
  const zip = zipSync({
    '3D/3dmodel.model': strToU8('<model/>'),
    'Metadata/plate_2.gcode': strToU8('; total estimated time: 9h\n'),
    'Metadata/plate_1.gcode': strToU8(HEADER + CONFIG),
    'Metadata/plate_1.png': new Uint8Array(64),
  });
  const r = await readSlicedFile(new File([zip], 'dice_tower.gcode.3mf'));
  assert.equal(r.ok, true);
  if (!r.ok) return;
  assert.equal(r.kind, '3mf');
  assert.equal(r.plate, 'plate_1.gcode');
  assert.match(r.notes[0], /2 plates/);
  assert.equal(parseGcode(r.text).durationMinutes, 134.13);
});

test('an unsliced 3MF project is refused with instructions', async () => {
  const zip = zipSync({ '3D/3dmodel.model': strToU8('<model/>') });
  const r = await readSlicedFile(new File([zip], 'project.3mf'));
  assert.equal(r.ok, false);
  if (r.ok) return;
  assert.match(r.message, /no sliced plate/);
});

test('Prusa binary gcode is refused by content, even if renamed', async () => {
  const r = await readSlicedFile(new File([new Uint8Array([0x47, 0x43, 0x44, 0x45, 1, 0, 0, 0])], 'renamed.gcode'));
  assert.equal(r.ok, false);
  if (r.ok) return;
  assert.match(r.message, /binary G-code/);
});

test('a damaged zip fails soft', async () => {
  const r = await readSlicedFile(new File([new Uint8Array([0x50, 0x4b, 3, 4, 9, 9, 9])], 'broken.3mf'));
  assert.equal(r.ok, false);
});

test('titleFromFileName', () => {
  assert.equal(titleFromFileName('dice_tower_PLA_2h14m.gcode.3mf'), 'dice tower PLA 2h14m');
  assert.equal(titleFromFileName('Benchy.gcode'), 'Benchy');
  assert.equal(titleFromFileName('part.GCO'), 'part');
});

// --------------------------------------------------------------------------
// matching
// --------------------------------------------------------------------------

const machines = [
  { id: 'm1', name: 'Garage P1S', make: 'Bambu Lab', model: 'P1S' },
  { id: 'm2', name: 'Office MK4', make: 'Prusa', model: 'MK4' },
  { id: 'm3', name: 'X', make: null, model: null },
];

test('machine match on model within the file string', () => {
  assert.deepEqual(matchMachines('Bambu Lab P1S', machines).map((m) => m.id), ['m1']);
  assert.deepEqual(matchMachines('MK4', machines).map((m) => m.id), ['m2']);
});

test('machine match ignores tiny tokens and missing models', () => {
  assert.deepEqual(matchMachines('Creality Ender-3 X', machines).map((m) => m.id), []);
  assert.deepEqual(matchMachines(null, machines), []);
});

const materials = [
  { id: 'a', name: 'Bambu Matte Black', category: 'PLA', brand: 'Bambu' },
  { id: 'b', name: 'Polymaker PLA Pro', category: 'PLA', brand: 'Polymaker' },
  { id: 'c', name: 'Overture PETG', category: 'PETG', brand: 'Overture' },
];

test('material: single category match is selected', () => {
  const r = matchMaterial('PETG', null, materials, '');
  assert.equal(r.kind, 'select');
  if (r.kind === 'select') assert.equal(r.material.id, 'c');
});

test('material: brand breaks a category tie', () => {
  const r = matchMaterial('PLA', 'Bambu PLA Matte @BBL P1S', materials, '');
  assert.equal(r.kind, 'select');
  if (r.kind === 'select') assert.equal(r.material.id, 'a');
});

test('material: a deliberate current choice in the category is kept', () => {
  const r = matchMaterial('PLA', 'Bambu PLA Matte', materials, 'b');
  assert.equal(r.kind, 'keep');
});

test('material: unresolved tie is ambiguous, not a guess', () => {
  const r = matchMaterial('PLA', null, materials, '');
  assert.equal(r.kind, 'ambiguous');
});

test('material: no category match', () => {
  assert.equal(matchMaterial('ASA', null, materials, '').kind, 'none');
  assert.equal(matchMaterial(null, null, materials, '').kind, 'none');
});
