// gcodeParse.test.ts
// Run with:  npm run test:gcode
// (node --experimental-strip-types src/lib/gcodeParse.test.ts)
//
// Fixtures are trimmed but structurally faithful to what each slicer writes.
// The duration assertions are the important ones: an earlier draft of the
// parser matched only PrusaSlicer's "= 1h 2m 3s" and silently returned null
// for OrcaSlicer and Bambu Studio, which is most of the market.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  parseGcode,
  parseAndValidate,
  validateParameters,
  hmsToMinutes,
  type ParameterDef,
} from './gcodeParse.ts';

// --------------------------------------------------------------------------
// fixtures
// --------------------------------------------------------------------------

const PRUSA = `
; generated by PrusaSlicer 2.8.1+win64 on 2026-01-14 at 09:12:44 UTC
M73 P0 R62
M201 X1000 Y1000 Z200 E5000
G28 ; home all
G1 Z0.2 F720
; filament used [mm] = 3521.09
; filament used [cm3] = 8.47
; filament used [g] = 10.50
; filament cost = 0.26
; total filament used [g] = 10.50
; estimated printing time (normal mode) = 1h 2m 3s
; estimated printing time (silent mode) = 1h 14m 9s
; prusaslicer_config = begin
; bed_temperature = 60
; brim_width = 0
; extrusion_multiplier = 0.98
; extrusion_width = 0.45
; fill_density = 15%
; fill_pattern = gyroid
; filament_diameter = 1.75
; filament_type = PLA
; filament_vendor = Prusa Polymers
; first_layer_bed_temperature = 60
; first_layer_height = 0.2
; first_layer_temperature = 215
; layer_height = 0.2
; nozzle_diameter = 0.4
; perimeter_speed = 45
; perimeters = 3
; printer_model = MK4
; raft_layers = 0
; retract_length = 0.8
; retract_speed = 35
; support_material = 0
; temperature = 210
; top_solid_layers = 5
; travel_speed = 180
; prusaslicer_config = end
`;

// Orca and Bambu use the colon form, and put two times on one line.
const ORCA = `
; generated by OrcaSlicer 2.2.0 on 2026-02-02 at 18:04:11
; model printing time: 2h 9m 12s; total estimated time: 2h 14m 8s
; total estimated time: 2h 14m 8s
; filament used [mm] = 15201.44
; filament used [cm3] = 36.56
; filament used [g] = 45.34
; total filament used [g] = 45.34
; filament_type = PETG
; filament_diameter = 1.75
; nozzle_temperature = 245
; nozzle_temperature_initial_layer = 250
; hot_plate_temp = 80
; layer_height = 0.2
; initial_layer_print_height = 0.24
; line_width = 0.42
; outer_wall_speed = 120
; initial_layer_speed = 30
; travel_speed = 350
; outer_wall_acceleration = 5000
; filament_flow_ratio = 0.95
; retraction_length = 0.8
; retraction_speed = 30
; sparse_infill_density = 20%
; sparse_infill_pattern = crosshatch
; wall_loops = 3
; top_shell_layers = 4
; fan_max_speed = 60
; enable_support = 1
; brim_type = outer_only
; brim_width = 5
; printer_model = Bambu Lab P1S
`;

// Bambu Studio: same family, multi-extruder AMS lists, no bare "filament used [g]".
const BAMBU_AMS = `
; generated by BambuStudio 1.10.1.50
; total estimated time: 45m 30s
; filament used [mm] = 4210.5,1180.2
; filament used [cm3] = 10.12,2.84
; filament used [g] = 12.55,3.52
; total filament used [g] = 16.07
; filament_type = PLA,PLA
; nozzle_temperature = 220,220
; hot_plate_temp = 55,55
; layer_height = 0.2
; sparse_infill_density = 10%
; wall_loops = 2
; retraction_length = 0.6
`;

// Cura writes a handful of comments and then plain commands.
const CURA = `
;FLAVOR:Marlin
;TIME:3723
;Filament used: 3.4512m
;Layer height: 0.16
;MINX:12.3
;MAXZ:40.0
;Generated with Cura_SteamEngine 5.8.0
M140 S60
M105
M190 S60
M104 S205
M109 S205
G28 ;Home
`;

// Bambu Studio's HEADER_BLOCK, as it opens a plate gcode inside a .gcode.3mf.
// Shape written from recollection of Bambu Studio 1.9/1.10 output and NOT
// yet checked against a real export: the M3 exit test replaces this with a
// real file's header. The config block that closes the file is omitted here
// on purpose, so this proves the header alone is enough.
const BAMBU_HEADER_ONLY = `
; HEADER_BLOCK_START
; BambuStudio 01.09.00.70
; model printing time: 1h 40m 5s; total estimated time: 1h 46m 43s
; total layer number: 150
; total filament length [mm] : 4520.08
; total filament volume [cm^3] : 10871.97
; total filament weight [g] : 13.48
; filament_density: 1.24
; filament_diameter: 1.75
; max_z_height: 30.00
; HEADER_BLOCK_END
`;

const NO_METADATA = `
G28
G1 X10 Y10 Z0.2 F1200
G1 X20 E1.5
`;

// A trimmed stand-in for `select ... from parameter_defs where domain_id='fdm'`.
const FDM_DEFS: ParameterDef[] = [
  { key: 'nozzle_temp', data_type: 'number', min_value: 150, max_value: 350, enum_options: null },
  { key: 'first_layer_temp', data_type: 'number', min_value: 150, max_value: 350, enum_options: null },
  { key: 'bed_temp', data_type: 'number', min_value: 0, max_value: 140, enum_options: null },
  { key: 'layer_height', data_type: 'number', min_value: 0.02, max_value: 1.2, enum_options: null },
  { key: 'first_layer_height', data_type: 'number', min_value: 0.05, max_value: 1.2, enum_options: null },
  { key: 'line_width', data_type: 'number', min_value: 0.1, max_value: 2.0, enum_options: null },
  { key: 'nozzle_diameter', data_type: 'number', min_value: 0.1, max_value: 2.0, enum_options: null },
  { key: 'print_speed', data_type: 'number', min_value: 1, max_value: 1000, enum_options: null },
  { key: 'first_layer_speed', data_type: 'number', min_value: 1, max_value: 500, enum_options: null },
  { key: 'travel_speed', data_type: 'number', min_value: 1, max_value: 1000, enum_options: null },
  { key: 'acceleration', data_type: 'number', min_value: 1, max_value: 50000, enum_options: null },
  { key: 'flow_rate', data_type: 'number', min_value: 50, max_value: 200, enum_options: null },
  { key: 'retraction_distance', data_type: 'number', min_value: 0, max_value: 20, enum_options: null },
  { key: 'retraction_speed', data_type: 'number', min_value: 1, max_value: 200, enum_options: null },
  { key: 'z_offset', data_type: 'number', min_value: -2, max_value: 2, enum_options: null },
  { key: 'infill_percent', data_type: 'number', min_value: 0, max_value: 100, enum_options: null },
  {
    key: 'infill_pattern',
    data_type: 'enum',
    min_value: null,
    max_value: null,
    enum_options: ['grid', 'gyroid', 'cubic', 'triangles', 'lightning', 'honeycomb', 'concentric', 'rectilinear'],
  },
  { key: 'wall_count', data_type: 'integer', min_value: 0, max_value: 20, enum_options: null },
  { key: 'top_bottom_layers', data_type: 'integer', min_value: 0, max_value: 20, enum_options: null },
  { key: 'cooling_fan_percent', data_type: 'number', min_value: 0, max_value: 100, enum_options: null },
  {
    key: 'bed_adhesion',
    data_type: 'enum',
    min_value: null,
    max_value: null,
    enum_options: ['none', 'skirt', 'brim', 'raft'],
  },
  { key: 'supports', data_type: 'boolean', min_value: null, max_value: null, enum_options: null },
  { key: 'filament_dried', data_type: 'boolean', min_value: null, max_value: null, enum_options: null },
  { key: 'chamber_temp', data_type: 'number', min_value: 0, max_value: 120, enum_options: null },
  { key: 'surface_prep', data_type: 'enum', min_value: null, max_value: null, enum_options: ['none', 'glue_stick'] },
];

// --------------------------------------------------------------------------
// duration helper
// --------------------------------------------------------------------------

test('hmsToMinutes handles every shape slicers emit', () => {
  assert.equal(hmsToMinutes('1h 2m 3s'), 62.05);
  assert.equal(hmsToMinutes('11m 6s'), 11.1);
  assert.equal(hmsToMinutes('45s'), 0.75);
  assert.equal(hmsToMinutes('2h'), 120);
  assert.equal(hmsToMinutes('1d 2h 30m'), 1590);
  assert.equal(hmsToMinutes('nonsense'), null);
  assert.equal(hmsToMinutes(null), null);
});

// --------------------------------------------------------------------------
// PrusaSlicer
// --------------------------------------------------------------------------

test('PrusaSlicer: duration, stated grams, and the settings block', () => {
  const r = parseGcode(PRUSA);
  assert.equal(r.durationMinutes, 62.05);
  assert.equal(r.materialQtyUsedG, 10.5);
  assert.equal(r.materialEstimated, false);
  assert.equal(r.materialSource, 'stated_grams');
  assert.equal(r.filamentType, 'PLA');
  assert.equal(r.printerModel, 'MK4');
  assert.match(r.slicer ?? '', /PrusaSlicer/);
  assert.equal(r.parameters.nozzle_temp, 210);
  assert.equal(r.parameters.first_layer_temp, 215);
  assert.equal(r.parameters.bed_temp, 60);
  assert.equal(r.parameters.layer_height, 0.2);
  assert.equal(r.parameters.retraction_distance, 0.8);
  assert.equal(r.parameters.retraction_speed, 35);
  assert.equal(r.parameters.print_speed, 45);
  assert.equal(r.parameters.wall_count, 3);
  assert.equal(r.parameters.infill_percent, 15);
  assert.equal(r.parameters.infill_pattern, 'gyroid');
  assert.equal(r.parameters.flow_rate, 98); // ratio 0.98 -> percent
  assert.equal(r.parameters.supports, false);
  assert.equal(r.parameters.bed_adhesion, undefined); // brim 0, raft 0, no brim_type
  assert.equal(r.warnings.length, 0);
});

// --------------------------------------------------------------------------
// OrcaSlicer : the regression that started this rewrite
// --------------------------------------------------------------------------

test('OrcaSlicer: colon-form duration is NOT dropped', () => {
  const r = parseGcode(ORCA);
  assert.equal(r.durationMinutes, 134.13, 'total estimated time, not model printing time');
});

test('OrcaSlicer: Orca-specific setting names all map', () => {
  const r = parseGcode(ORCA);
  assert.equal(r.materialQtyUsedG, 45.34);
  assert.equal(r.materialEstimated, false);
  assert.equal(r.filamentType, 'PETG');
  assert.equal(r.parameters.nozzle_temp, 245);
  assert.equal(r.parameters.first_layer_temp, 250);
  assert.equal(r.parameters.bed_temp, 80); // hot_plate_temp
  assert.equal(r.parameters.line_width, 0.42);
  assert.equal(r.parameters.print_speed, 120); // outer_wall_speed
  assert.equal(r.parameters.first_layer_speed, 30);
  assert.equal(r.parameters.acceleration, 5000);
  assert.equal(r.parameters.flow_rate, 95); // filament_flow_ratio 0.95
  assert.equal(r.parameters.retraction_distance, 0.8);
  assert.equal(r.parameters.infill_percent, 20);
  assert.equal(r.parameters.infill_pattern, 'grid'); // crosshatch normalised
  assert.equal(r.parameters.wall_count, 3);
  assert.equal(r.parameters.top_bottom_layers, 4);
  assert.equal(r.parameters.cooling_fan_percent, 60);
  assert.equal(r.parameters.supports, true);
  assert.equal(r.parameters.bed_adhesion, 'brim');
});

// --------------------------------------------------------------------------
// Bambu Studio
// --------------------------------------------------------------------------

test('Bambu Studio: colon duration and summed multi-extruder material', () => {
  const r = parseGcode(BAMBU_AMS);
  assert.equal(r.durationMinutes, 45.5);
  assert.equal(r.materialQtyUsedG, 16.07, 'both AMS slots, not just the first');
  assert.equal(r.materialEstimated, false);
  assert.equal(r.filamentType, 'PLA');
  assert.equal(r.parameters.nozzle_temp, 220, 'temperatures take the first value, not the sum');
  assert.equal(r.parameters.bed_temp, 55);
});

// --------------------------------------------------------------------------
// Cura
// --------------------------------------------------------------------------

test('Cura: seconds, metres, and temperatures recovered from commands', () => {
  const r = parseGcode(CURA);
  assert.equal(r.durationMinutes, 62.05);
  assert.equal(r.materialEstimated, true);
  assert.equal(r.materialSource, 'from_length');
  // 3451.2mm of 1.75mm PLA -> pi*(0.875^2)*3451.2 mm3 = 8302.5 mm3 -> 10.29 g
  assert.ok(
    r.materialQtyUsedG !== null && Math.abs(r.materialQtyUsedG - 10.29) < 0.05,
    `expected ~10.29g, got ${r.materialQtyUsedG}`,
  );
  assert.equal(r.parameters.layer_height, 0.16);
  assert.equal(r.parameters.nozzle_temp, 205);
  assert.equal(r.parameters.bed_temp, 60);
  assert.equal(r.raw.nozzle_temp_source, 'M104/M109 command, not a settings comment');
});

// --------------------------------------------------------------------------
// degenerate input
// --------------------------------------------------------------------------

test('Bambu Studio header block alone: duration, stated grams, slicer', () => {
  const r = parseGcode(BAMBU_HEADER_ONLY);
  assert.equal(r.durationMinutes, 106.72, 'total estimated time, 1h 46m 43s');
  assert.equal(r.materialQtyUsedG, 13.48);
  assert.equal(r.materialSource, 'stated_grams');
  assert.equal(r.slicer, 'BambuStudio 01.09.00.70');
});

test('Bambu header: the [cm^3] volume line is never used, even without grams', () => {
  const noGrams = BAMBU_HEADER_ONLY.replace(/^; total filament weight.*$/m, '');
  const r = parseGcode(noGrams);
  // Falls to length x geometry (4520.08 mm of 1.75 mm at 1.24) = 13.49 g,
  // not 10871.97 x 1.24 = 13481 g from the mislabelled volume.
  assert.equal(r.materialSource, 'from_length');
  assert.ok(r.materialQtyUsedG !== null && Math.abs(r.materialQtyUsedG - 13.49) < 0.05, `got ${r.materialQtyUsedG}`);
});

test('the file density is preferred over the lookup table', () => {
  const r = parseGcode('; filament_type = PETG\n; filament_density: 1.30\n; filament used [mm] = 1000\n');
  // 1000 mm x pi x 0.875^2 = 2405.28 mm3 = 2.405 cm3; x 1.30 = 3.13 g (PETG table would give 3.05)
  assert.equal(r.materialQtyUsedG, 3.13);
});

test('a file with no metadata fails soft, with warnings instead of an exception', () => {
  const r = parseGcode(NO_METADATA);
  assert.equal(r.durationMinutes, null);
  assert.equal(r.materialQtyUsedG, null);
  assert.equal(r.materialSource, null);
  assert.equal(r.warnings.length, 2);
});

test('an empty string does not throw', () => {
  const r = parseGcode('');
  assert.equal(r.durationMinutes, null);
  assert.deepEqual(r.parameters, {});
});

// --------------------------------------------------------------------------
// dictionary discipline
// --------------------------------------------------------------------------

test('validateParameters drops keys the dictionary does not define', () => {
  const v = validateParameters({ nozzle_temp: 210, made_up_key: 5 }, FDM_DEFS);
  assert.equal(v.accepted.nozzle_temp, 210);
  assert.equal('made_up_key' in v.accepted, false);
  assert.equal(v.rejected.made_up_key, 'not defined for this domain');
});

test('validateParameters clamps out-of-range numbers and records the original', () => {
  const v = validateParameters({ nozzle_temp: 900, infill_percent: -4 }, FDM_DEFS);
  assert.equal(v.accepted.nozzle_temp, 350);
  assert.deepEqual(v.clamped.nozzle_temp, [900, 350]);
  assert.equal(v.accepted.infill_percent, 0);
});

test('validateParameters rejects an enum value outside enum_options', () => {
  const v = validateParameters({ infill_pattern: 'spaghetti' }, FDM_DEFS);
  assert.equal('infill_pattern' in v.accepted, false);
  assert.match(v.rejected.infill_pattern, /not one of/);
});

test('validateParameters rounds integers', () => {
  const v = validateParameters({ wall_count: 2.7 }, FDM_DEFS);
  assert.equal(v.accepted.wall_count, 3);
});

test('parseAndValidate returns only dictionary-legal keys', () => {
  const r = parseAndValidate(ORCA, FDM_DEFS);
  for (const key of Object.keys(r.parameters)) {
    assert.ok(
      FDM_DEFS.some((d) => d.key === key),
      `${key} is not in parameter_defs`,
    );
  }
  assert.equal(r.parameters.nozzle_temp, 245);
  assert.deepEqual(r.validation.rejected, {});
});

test('every parsed key across all fixtures exists in parameter_defs', () => {
  const known = new Set(FDM_DEFS.map((d) => d.key));
  for (const [name, fixture] of Object.entries({ PRUSA, ORCA, BAMBU_AMS, CURA })) {
    for (const key of Object.keys(parseGcode(fixture).parameters)) {
      assert.ok(known.has(key), `${name} produced unknown key: ${key}`);
    }
  }
});
