// ingest.test.ts
// Run with:  npm run test:ingest

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { UPLOAD_TOKEN_RE, bearerToken, buildIngest, cleanFileName, ingestErrorResponse } from './ingest.ts';
import { hashToken, newUploadToken } from './upload-tokens.ts';

const ORCA = `
; generated by OrcaSlicer 2.2.0 on 2026-02-02 at 18:04:11
; total estimated time: 2h 14m 8s
G28
G1 X10 Y10 E1
; filament used [g] = 45.34
; CONFIG_BLOCK_START
; nozzle_temperature = 245
; filament_type = PETG
; printer_model = Bambu Lab P1S
; machine_start_gcode = G28\\nG29
; CONFIG_BLOCK_END
`;

test('a new token matches the pattern the database checks, and hashes the same way every time', () => {
  const t = newUploadToken();
  assert.match(t.token, UPLOAD_TOKEN_RE);
  assert.equal(t.token.length, 47);
  assert.match(t.hash, /^[0-9a-f]{64}$/);
  assert.equal(hashToken(t.token), t.hash);
  assert.equal(t.prefix, t.token.slice(0, 10));
  assert.notEqual(newUploadToken().token, t.token);
});

test('known SHA-256 so the app and pgcrypto agree', () => {
  // Same value as: select encode(extensions.digest('ssk_test', 'sha256'), 'hex');
  assert.equal(hashToken('ssk_test'), 'fa9aaa060c61f7c96f3f96aaa4789f8b9be54158a75387b612a704777f08fc97');
});

test('bearer header parsing accepts only a well-formed token', () => {
  const t = newUploadToken().token;
  assert.equal(bearerToken(`Bearer ${t}`), t);
  assert.equal(bearerToken(`bearer ${t} `), t);
  assert.equal(bearerToken(null), null);
  assert.equal(bearerToken('Bearer abc'), null);
  assert.equal(bearerToken(t), null);
});

test('file names lose folders and control characters', () => {
  assert.equal(cleanFileName('C:\\Users\\terry\\AppData\\Local\\Temp\\foot plate.gcode'), 'foot plate.gcode');
  assert.equal(cleanFileName('/tmp/x/cube.gcode'), 'cube.gcode');
  assert.equal(cleanFileName('bad\u0007name.gcode'), 'badname.gcode');
  assert.equal(cleanFileName(''), 'sliced file');
  assert.equal(cleanFileName(42), 'sliced file');
  assert.equal(cleanFileName('a'.repeat(400)).length, 255);
});

test('an Orca upload becomes a pending run with parsed values and the config', () => {
  const r = buildIngest({ file_name: 'C:\\Temp\\bracket.gcode', text: ORCA });
  assert.equal(r.ok, true);
  if (!r.ok) return;
  assert.equal(r.args.p_file_name, 'bracket.gcode');
  assert.equal(r.args.p_printer_model, 'Bambu Lab P1S');
  assert.equal(r.args.p_duration_minutes, 134.13);
  assert.equal(r.args.p_material_g, 45.34);
  assert.equal(r.args.p_parsed.filamentType, 'PETG');
  assert.equal(r.args.p_parsed.parser_version, 2);
  assert.equal(r.args.p_parsed.config_format, 'bambu_orca');
  assert.equal(r.args.p_slicer_config?.nozzle_temperature, '245');
  assert.equal(r.args.p_slicer_config?.machine_start_gcode, undefined);
});

test('bad uploads are refused with a status the script understands', () => {
  const cases: [unknown, number][] = [
    [null, 400],
    [[], 400],
    [{ file_name: 'x' }, 400],
    [{ file_name: 'x', text: '' }, 400],
    [{ file_name: 'x', text: 'G28\nG1 X1 Y1\n' }, 422],
    [{ file_name: 'x', text: 'GCDE\u0001\u0000' }, 422],
    [{ file_name: 'x', text: 'x'.repeat(3_000_001) }, 413],
  ];
  for (const [body, status] of cases) {
    const r = buildIngest(body);
    assert.equal(r.ok, false);
    if (!r.ok) assert.equal(r.status, status, JSON.stringify(body).slice(0, 40));
  }
});

test('database errors map to statuses the script acts on', () => {
  assert.equal(ingestErrorResponse({ code: '28000' }).status, 401);
  assert.equal(ingestErrorResponse({ code: '54000' }).status, 429);
  assert.equal(ingestErrorResponse({ code: '23514' }).status, 413);
  assert.equal(ingestErrorResponse({ code: 'XX000' }).status, 500);
  assert.equal(ingestErrorResponse({}).status, 500);
});
