// slicer-config.test.ts
// Run with:  npm run test:slicer-config

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { SLICER_CONFIG_MAX_BYTES, extractSlicerConfig, sanitizeSlicerConfig } from './slicer-config.ts';

const PRUSA = `
; generated by PrusaSlicer 2.8.1+win64
; estimated printing time (normal mode) = 1h 2m 3s
; prusaslicer_config = begin
; bed_temperature = 60
; fill_density = 15%
; layer_height = 0.2
; start_gcode = M115 U3.13.0 ; tell printer latest fw version\\nG90
; post_process = "C:\\Users\\someone\\scripts\\upload.py"
; temperature = 210
; temperature = 999
; prusaslicer_config = end
`;

const BAMBU = `
; HEADER_BLOCK_START
; BambuStudio 02.08.02.60
; total estimated time: 4h 26m 59s
; HEADER_BLOCK_END
; CONFIG_BLOCK_START
; curr_bed_type = High Temp Plate
; filament_settings_id = "Bambu PLA Basic @BBL A1"
; machine_start_gcode = ;===== machine: A1 =====\\nG392 S0
; nozzle_temperature = 220
; print_host = 192.168.1.20
; printhost_apikey = abc123
; sparse_infill_density = 15%
; empty_value =
; CONFIG_BLOCK_END
; EXECUTABLE_BLOCK_START
; this = not config
`;

const CURA = `
;FLAVOR:Marlin
;TIME:6127
;Generated with Cura_SteamEngine 5.7.1
;SETTING_3 {"global_quality": "[general]\\nversion = 4"}
`;

test('Prusa config block: every setting kept, first value wins', () => {
  const r = extractSlicerConfig(PRUSA);
  assert.equal(r.format, 'prusa');
  assert.equal(r.config?.bed_temperature, '60');
  assert.equal(r.config?.fill_density, '15%');
  assert.equal(r.config?.temperature, '210');
  assert.equal(Object.keys(r.config ?? {}).length, 4);
});

test('G-code templates and disk paths are left out', () => {
  const r = extractSlicerConfig(PRUSA);
  assert.equal(r.config?.start_gcode, undefined);
  assert.equal(r.config?.post_process, undefined);
  assert.equal(r.skipped, 2);
});

test('Bambu and Orca config block, credentials and print host dropped', () => {
  const r = extractSlicerConfig(BAMBU);
  assert.equal(r.format, 'bambu_orca');
  assert.equal(r.config?.nozzle_temperature, '220');
  assert.equal(r.config?.curr_bed_type, 'High Temp Plate');
  assert.equal(r.config?.filament_settings_id, '"Bambu PLA Basic @BBL A1"');
  assert.equal(r.config?.empty_value, '');
  assert.equal(r.config?.machine_start_gcode, undefined);
  assert.equal(r.config?.print_host, undefined);
  assert.equal(r.config?.printhost_apikey, undefined);
  assert.equal(r.config?.this, undefined, 'nothing after the block end is read');
  assert.equal(r.skipped, 3);
});

test('Cura and files with no config block give null, not an empty object', () => {
  assert.deepEqual(extractSlicerConfig(CURA), { config: null, format: null, skipped: 0 });
  assert.deepEqual(extractSlicerConfig('G28\nG1 X10'), { config: null, format: null, skipped: 0 });
});

test('the size cap holds however big the block is', () => {
  const lines = Array.from({ length: 1500 }, (_, i) => `; setting_${i} = ${'x'.repeat(200)}`);
  const text = `; CONFIG_BLOCK_START\n${lines.join('\n')}\n; CONFIG_BLOCK_END\n`;
  const r = extractSlicerConfig(text);
  const size = new TextEncoder().encode(JSON.stringify(r.config)).length;
  assert.ok(size <= SLICER_CONFIG_MAX_BYTES, `stored ${size} bytes`);
  assert.ok(r.skipped > 0);
  assert.equal(Object.keys(r.config ?? {}).length + r.skipped, 1500);
});

test('server check accepts what the extractor produces and refuses anything else', () => {
  const r = extractSlicerConfig(BAMBU);
  assert.deepEqual(sanitizeSlicerConfig(r.config), r.config);
  assert.equal(sanitizeSlicerConfig(null), null);
  assert.equal(sanitizeSlicerConfig([1, 2]), null);
  assert.equal(sanitizeSlicerConfig({ a: 1 }), null);
  assert.equal(sanitizeSlicerConfig({ a: 'x'.repeat(1001) }), null);
  assert.equal(sanitizeSlicerConfig({}), null);
  // A forged credential key is dropped, not stored.
  assert.deepEqual(sanitizeSlicerConfig({ layer_height: '0.2', printhost_apikey: 'k' }), { layer_height: '0.2' });
});
