-- =====================================================================
-- SpoolStack (Maker Run Log) : Phase 1 "The Spine" schema
-- Target: Supabase Postgres 15+ (tested on PostgreSQL 16.13)
--
-- Run this whole file in the Supabase SQL editor. It is IDEMPOTENT:
-- running it twice is safe and changes nothing the second time.
--
-- Design contract (see the build plan doc):
--   * Rigid columns for what every run shares across FDM / CNC / resin / laser.
--   * A JSONB `parameters` bag for domain-specific settings.
--   * `parameter_defs` disciplines that bag AND drives the run form UI.
--   * Cost is NEVER stored. Runs store raw measurements; cost is derived
--     at read time by the run_cost_breakdown view.
--   * Adding a domain (CNC, resin, laser) = INSERT into reference tables.
--     No ALTER TABLE, no migration.
--
-- Section map:
--   0. Extensions and helpers
--   1. Reference tables (the template system): domains, parameter_defs, defect_types
--   2. User setup tables: user_settings, machines, materials, projects
--   3. The spine: runs, run_defects
--   4. Derived cost view
--   5. Indexes
--   6. Row Level Security
--   7. Grants
--   8. FDM seed data
-- =====================================================================


-- =====================================================================
-- 0. EXTENSIONS AND HELPERS
-- =====================================================================

-- gen_random_uuid() is in pg_catalog on PG13+; pgcrypto kept for older targets.
create extension if not exists pgcrypto with schema extensions;

-- NOTE: named dollar-quote tags throughout. Bare $$ has thrown
-- "unterminated dollar-quoted string" in the Supabase SQL editor.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $set_updated_at$
begin
  new.updated_at = now();
  return new;
end;
$set_updated_at$;

comment on function public.set_updated_at() is
  'BEFORE UPDATE trigger: stamps updated_at. Returns NEW (never OLD) so the row actually writes.';


-- =====================================================================
-- 1. REFERENCE TABLES  (these three tables ARE the template system)
-- =====================================================================

-- ---- domains --------------------------------------------------------
create table if not exists public.domains (
  id            text primary key,                      -- 'fdm', 'cnc', 'resin', 'laser'
  display_name  text        not null,
  description   text,
  unit_label    text        not null default 'g',      -- default consumption unit for the domain
  sort_order    integer     not null default 0,
  is_active     boolean     not null default true,
  created_at    timestamptz not null default now()
);

comment on table public.domains is
  'One row per manufacturing process. Phase 5 expansion = INSERT here plus parameter_defs and defect_types.';


-- ---- parameter_defs -------------------------------------------------
-- Governs which keys may appear in runs.parameters, renders the run form,
-- and tells the Phase 3 oracle which parameters are worth modelling on.
create table if not exists public.parameter_defs (
  id                       bigint generated by default as identity primary key,
  domain_id                text    not null references public.domains(id) on delete cascade,
  key                      text    not null,           -- the JSONB key, e.g. 'nozzle_temp'
  display_name             text    not null,
  group_name               text    not null default 'General',  -- form section heading
  data_type                text    not null default 'number'
                             check (data_type in ('number','integer','boolean','text','enum')),
  unit                     text,                       -- 'C', 'mm', 'mm/s', '%'
  min_value                numeric,
  max_value                numeric,
  step                     numeric,
  enum_options             text[],
  default_value            text,                       -- string form; cast per data_type in the UI
  is_required              boolean not null default false,
  is_calibration_relevant  boolean not null default false,
  help_text                text,
  sort_order               integer not null default 0,
  is_active                boolean not null default true,
  created_at               timestamptz not null default now(),
  constraint parameter_defs_domain_key_uniq unique (domain_id, key),
  constraint parameter_defs_key_shape
    check (key ~ '^[a-z][a-z0-9_]*$'),
  constraint parameter_defs_enum_has_options
    check (data_type <> 'enum' or (enum_options is not null and cardinality(enum_options) > 0)),
  constraint parameter_defs_range_sane
    check (min_value is null or max_value is null or min_value <= max_value)
);

comment on column public.parameter_defs.is_calibration_relevant is
  'Phase 3 reads only these keys when modelling what settings predict a good outcome.';


-- ---- defect_types ---------------------------------------------------
create table if not exists public.defect_types (
  id                 bigint generated by default as identity primary key,
  domain_id          text    not null references public.domains(id) on delete cascade,
  key                text    not null,                 -- 'stringing'
  display_name       text    not null,
  description        text,
  likely_causes      text[]  not null default '{}',    -- parameter_defs.key values, Phase 4 grounding
  is_process_related boolean not null default true,    -- false = external event (runout, power loss)
  sort_order         integer not null default 0,
  is_active          boolean not null default true,
  created_at         timestamptz not null default now(),
  constraint defect_types_domain_key_uniq unique (domain_id, key),
  constraint defect_types_key_shape check (key ~ '^[a-z][a-z0-9_]*$')
);

comment on column public.defect_types.is_process_related is
  'False for failures no setting could have prevented (filament runout, power cut, knocked part). '
  'Phase 2 costing counts them; Phase 3 calibration must NOT learn from them.';


-- =====================================================================
-- 2. USER SETUP TABLES
-- =====================================================================

-- ---- user_settings --------------------------------------------------
-- Rates are deliberately NULLABLE with no default. A wrong default silently
-- produces a confident wrong cost; a NULL makes the cost view report the
-- input as missing instead.
create table if not exists public.user_settings (
  user_id                  uuid primary key references auth.users(id) on delete cascade,
  display_name             text,
  currency                 text    not null default 'USD',
  electricity_rate_per_kwh numeric(10,4) check (electricity_rate_per_kwh >= 0),
  labor_rate_per_hour      numeric(10,2) check (labor_rate_per_hour >= 0),
  include_labor_in_cost    boolean not null default false,
  default_domain_id        text references public.domains(id),
  units                    text    not null default 'metric' check (units in ('metric','imperial')),
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

drop trigger if exists trg_user_settings_updated_at on public.user_settings;
create trigger trg_user_settings_updated_at
  before update on public.user_settings
  for each row execute function public.set_updated_at();


-- ---- machines -------------------------------------------------------
create table if not exists public.machines (
  id                        uuid primary key default gen_random_uuid(),
  user_id                   uuid not null references auth.users(id) on delete cascade,
  domain_id                 text not null references public.domains(id),
  name                      text not null,
  make                      text,
  model                     text,
  purchase_cost             numeric(12,2) check (purchase_cost >= 0),
  expected_life_hours       numeric(10,1) check (expected_life_hours > 0),
  power_watts               numeric(10,1) check (power_watts >= 0),
  maintenance_cost_per_hour numeric(10,4) check (maintenance_cost_per_hour >= 0),
  build_volume              text,
  nozzle_diameter_mm        numeric(5,2),
  commissioned_on           date,
  notes                     text,
  is_active                 boolean not null default true,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  constraint machines_user_name_uniq unique (user_id, name)
);

comment on column public.machines.power_watts is
  'Average draw while running, in watts. Measure with a plug meter for a real number; '
  'nameplate wattage overstates it badly on FDM printers.';

drop trigger if exists trg_machines_updated_at on public.machines;
create trigger trg_machines_updated_at
  before update on public.machines
  for each row execute function public.set_updated_at();


-- ---- materials ------------------------------------------------------
create table if not exists public.materials (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users(id) on delete cascade,
  domain_id      text not null references public.domains(id),
  name           text not null,                        -- 'Prusament PLA Galaxy Black'
  category       text,                                 -- 'PLA' ; matched against gcode filament_type
  brand          text,
  color          text,
  unit           text not null default 'g'
                   check (unit in ('g','kg','ml','l','mm','m','cm3','sheet','each')),
  cost_per_unit  numeric(12,4) check (cost_per_unit >= 0),   -- AUTHORITATIVE for costing
  package_qty    numeric(12,3) check (package_qty > 0),      -- entry aid: 1000 (g)
  package_cost   numeric(12,2) check (package_cost >= 0),    -- entry aid: 24.99
  density_g_cm3  numeric(6,3) check (density_g_cm3 > 0),     -- gcode length -> mass
  diameter_mm    numeric(5,2) check (diameter_mm > 0),       -- filament diameter, same purpose
  spool_weight_g numeric(8,2),
  notes          text,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint materials_user_name_uniq unique (user_id, name)
);

comment on column public.materials.cost_per_unit is
  'The single source of truth for material cost. The UI computes it from package_cost/package_qty '
  'when those are entered, but never reads them at costing time.';

drop trigger if exists trg_materials_updated_at on public.materials;
create trigger trg_materials_updated_at
  before update on public.materials
  for each row execute function public.set_updated_at();


-- ---- projects -------------------------------------------------------
create table if not exists public.projects (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users(id) on delete cascade,
  name        text not null,
  description text,
  client      text,
  status      text not null default 'active' check (status in ('active','archived')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint projects_user_name_uniq unique (user_id, name)
);

drop trigger if exists trg_projects_updated_at on public.projects;
create trigger trg_projects_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();


-- =====================================================================
-- 3. THE SPINE
-- =====================================================================

-- ---- runs -----------------------------------------------------------
-- One row per job: one print today, one CNC cut or laser pass later.
-- NOTE: no cost columns. Ever. See section 4.
create table if not exists public.runs (
  id                     uuid primary key default gen_random_uuid(),
  user_id                uuid not null references auth.users(id) on delete cascade,
  domain_id              text not null references public.domains(id),
  project_id             uuid references public.projects(id) on delete set null,
  machine_id             uuid references public.machines(id) on delete set null,
  material_id            uuid references public.materials(id) on delete set null,

  title                  text,
  started_at             timestamptz,
  completed_at           timestamptz,

  -- raw consumption measurements (cost inputs, never cost)
  duration_minutes       numeric(10,2) check (duration_minutes >= 0),
  material_qty_used      numeric(12,3) check (material_qty_used >= 0),
  material_qty_estimated boolean not null default false,  -- true when derived from length, not weighed
  active_labor_minutes   numeric(10,2) not null default 0 check (active_labor_minutes >= 0),

  -- batch economics: Phase 2's marginal-cost curve cannot be backfilled
  units_produced         integer not null default 1 check (units_produced > 0),
  units_good             integer check (units_good >= 0),

  outcome                text not null check (outcome in ('success','partial','failure','aborted')),
  quality_rating         smallint check (quality_rating between 1 and 5),

  parameters             jsonb not null default '{}'::jsonb,
  notes                  text,
  photos                 text[] not null default '{}',   -- storage object paths, Phase 4
  tags                   text[] not null default '{}',

  source                 text not null default 'manual'
                           check (source in ('manual','gcode_import','api')),
  source_metadata        jsonb not null default '{}'::jsonb,  -- the parser's raw matches

  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  constraint runs_units_good_lte_produced
    check (units_good is null or units_good <= units_produced),
  constraint runs_completed_after_started
    check (started_at is null or completed_at is null or completed_at >= started_at),
  constraint runs_parameters_is_object
    check (jsonb_typeof(parameters) = 'object'),
  constraint runs_source_metadata_is_object
    check (jsonb_typeof(source_metadata) = 'object')
);

comment on table public.runs is
  'The event log. Every later feature is a query against this table, not a migration of it.';
comment on column public.runs.units_produced is
  'Parts on the plate. Required for per-unit cost and the Phase 2 economies-of-scale curve. '
  'Defaults to 1 so it never blocks a fast log entry, but it cannot be reconstructed later.';
comment on column public.runs.material_qty_estimated is
  'True when the quantity came from a slicer length estimate rather than a scale. '
  'Phase 2 should surface this; estimated masses carry real error.';

drop trigger if exists trg_runs_updated_at on public.runs;
create trigger trg_runs_updated_at
  before update on public.runs
  for each row execute function public.set_updated_at();


-- ---- run_defects ----------------------------------------------------
create table if not exists public.run_defects (
  id             bigint generated by default as identity primary key,
  run_id         uuid   not null references public.runs(id) on delete cascade,
  defect_type_id bigint not null references public.defect_types(id),
  severity       smallint check (severity between 1 and 5),
  notes          text,
  photo_path     text,
  created_at     timestamptz not null default now(),
  constraint run_defects_run_type_uniq unique (run_id, defect_type_id)
);

comment on table public.run_defects is
  'Many defects per run. Phase 4 writes here from photo analysis; Phase 3 reads it as correction signal.';


-- =====================================================================
-- 4. DERIVED COST VIEW  (this is the whole of Phase 2's plumbing)
-- =====================================================================
-- security_invoker = true is REQUIRED. Without it the view runs as its
-- owner and bypasses RLS on the underlying tables, exposing every user's
-- runs to every user. This is the single most dangerous line in the file.

drop view if exists public.run_cost_breakdown;

create view public.run_cost_breakdown
with (security_invoker = true) as
with base as (
  select
    r.id                as run_id,
    r.user_id,
    r.domain_id,
    r.project_id,
    r.machine_id,
    r.material_id,
    r.title,
    r.outcome,
    r.units_produced,
    r.units_good,
    r.duration_minutes,
    r.material_qty_used,
    r.material_qty_estimated,
    r.active_labor_minutes,
    r.created_at,
    mt.cost_per_unit    as material_cost_per_unit,
    mc.power_watts,
    mc.purchase_cost    as machine_purchase_cost,
    mc.expected_life_hours,
    mc.maintenance_cost_per_hour,
    us.electricity_rate_per_kwh,
    us.labor_rate_per_hour,
    us.include_labor_in_cost,
    us.currency
  from public.runs r
  left join public.materials     mt on mt.id      = r.material_id
  left join public.machines      mc on mc.id      = r.machine_id
  left join public.user_settings us on us.user_id = r.user_id
),
priced as (
  select
    base.*,
    round(base.material_qty_used * base.material_cost_per_unit, 4)
      as material_cost,
    round((base.power_watts / 1000.0)
          * (base.duration_minutes / 60.0)
          * base.electricity_rate_per_kwh, 4)
      as energy_cost,
    round(( (base.machine_purchase_cost / nullif(base.expected_life_hours, 0))
            + coalesce(base.maintenance_cost_per_hour, 0) )
          * (base.duration_minutes / 60.0), 4)
      as machine_cost,
    case
      when coalesce(base.include_labor_in_cost, false)
        then round((base.active_labor_minutes / 60.0) * base.labor_rate_per_hour, 4)
      else 0::numeric
    end as labor_cost,
    array_remove(array[
      case when base.duration_minutes is null          then 'duration_minutes' end,
      case when base.material_id is null               then 'material' end,
      case when base.material_qty_used is null         then 'material_qty_used' end,
      case when base.material_cost_per_unit is null    then 'material_cost_per_unit' end,
      case when base.machine_id is null                then 'machine' end,
      case when base.power_watts is null               then 'machine_power_watts' end,
      case when base.electricity_rate_per_kwh is null  then 'electricity_rate_per_kwh' end,
      case when base.machine_purchase_cost is null
             or base.expected_life_hours is null       then 'machine_depreciation_inputs' end,
      case when coalesce(base.include_labor_in_cost, false)
             and base.labor_rate_per_hour is null      then 'labor_rate_per_hour' end
    ], null) as missing_inputs
  from base
)
select
  priced.*,
  ( coalesce(priced.material_cost, 0)
  + coalesce(priced.energy_cost,   0)
  + coalesce(priced.machine_cost,  0)
  + coalesce(priced.labor_cost,    0) )                                   as total_cost,
  round(( coalesce(priced.material_cost, 0)
        + coalesce(priced.energy_cost,   0)
        + coalesce(priced.machine_cost,  0)
        + coalesce(priced.labor_cost,    0) )
        / nullif(priced.units_produced, 0), 4)                            as cost_per_unit_produced,
  round(( coalesce(priced.material_cost, 0)
        + coalesce(priced.energy_cost,   0)
        + coalesce(priced.machine_cost,  0)
        + coalesce(priced.labor_cost,    0) )
        / nullif(coalesce(priced.units_good, priced.units_produced), 0), 4)
                                                                          as cost_per_good_unit,
  (cardinality(priced.missing_inputs) = 0)                                as cost_complete
from priced;

comment on view public.run_cost_breakdown is
  'Phase 2 reads this. Costs recompute from current rates, so editing a material price or the '
  'power rate corrects every historical run. cost_complete/missing_inputs say when a number is '
  'partial rather than quietly summing zeros.';


-- =====================================================================
-- 5. INDEXES
-- =====================================================================

create index if not exists idx_runs_user_created         on public.runs (user_id, created_at desc);
create index if not exists idx_runs_user_material        on public.runs (user_id, material_id, outcome);
create index if not exists idx_runs_user_machine         on public.runs (user_id, machine_id, outcome);
create index if not exists idx_runs_user_project         on public.runs (user_id, project_id);
create index if not exists idx_runs_user_domain          on public.runs (user_id, domain_id, created_at desc);
create index if not exists idx_runs_user_outcome         on public.runs (user_id, outcome);
-- GIN on the parameter bag: keeps `parameters @> '{"nozzle_temp":210}'` fast
-- once Phase 3 calibration queries arrive.
create index if not exists idx_runs_parameters_gin       on public.runs using gin (parameters jsonb_path_ops);
create index if not exists idx_runs_tags_gin             on public.runs using gin (tags);

create index if not exists idx_run_defects_run           on public.run_defects (run_id);
create index if not exists idx_run_defects_type          on public.run_defects (defect_type_id);

create index if not exists idx_machines_user_active      on public.machines  (user_id) where is_active;
create index if not exists idx_materials_user_active     on public.materials (user_id) where is_active;
create index if not exists idx_materials_user_category   on public.materials (user_id, category);
create index if not exists idx_projects_user_status      on public.projects  (user_id, status);

create index if not exists idx_parameter_defs_domain     on public.parameter_defs (domain_id, sort_order) where is_active;
create index if not exists idx_defect_types_domain       on public.defect_types   (domain_id, sort_order) where is_active;


-- =====================================================================
-- 6. ROW LEVEL SECURITY
-- =====================================================================
-- Policies use (select auth.uid()) rather than bare auth.uid(): the
-- subquery form is evaluated once as an InitPlan instead of once per row.
-- On a 5,000-run journal query that difference is visible.

alter table public.domains        enable row level security;
alter table public.parameter_defs enable row level security;
alter table public.defect_types   enable row level security;
alter table public.user_settings  enable row level security;
alter table public.machines       enable row level security;
alter table public.materials      enable row level security;
alter table public.projects       enable row level security;
alter table public.runs           enable row level security;
alter table public.run_defects    enable row level security;

-- ---- reference tables: readable by any signed-in user, writable by none
drop policy if exists domains_read        on public.domains;
create policy domains_read        on public.domains        for select to authenticated using (true);

drop policy if exists parameter_defs_read on public.parameter_defs;
create policy parameter_defs_read on public.parameter_defs for select to authenticated using (true);

drop policy if exists defect_types_read   on public.defect_types;
create policy defect_types_read   on public.defect_types   for select to authenticated using (true);

-- ---- user_settings
drop policy if exists user_settings_select on public.user_settings;
create policy user_settings_select on public.user_settings for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists user_settings_insert on public.user_settings;
create policy user_settings_insert on public.user_settings for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists user_settings_update on public.user_settings;
create policy user_settings_update on public.user_settings for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists user_settings_delete on public.user_settings;
create policy user_settings_delete on public.user_settings for delete to authenticated
  using ((select auth.uid()) = user_id);

-- ---- machines
drop policy if exists machines_select on public.machines;
create policy machines_select on public.machines for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists machines_insert on public.machines;
create policy machines_insert on public.machines for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists machines_update on public.machines;
create policy machines_update on public.machines for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists machines_delete on public.machines;
create policy machines_delete on public.machines for delete to authenticated
  using ((select auth.uid()) = user_id);

-- ---- materials
drop policy if exists materials_select on public.materials;
create policy materials_select on public.materials for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists materials_insert on public.materials;
create policy materials_insert on public.materials for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists materials_update on public.materials;
create policy materials_update on public.materials for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists materials_delete on public.materials;
create policy materials_delete on public.materials for delete to authenticated
  using ((select auth.uid()) = user_id);

-- ---- projects
drop policy if exists projects_select on public.projects;
create policy projects_select on public.projects for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists projects_insert on public.projects;
create policy projects_insert on public.projects for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists projects_update on public.projects;
create policy projects_update on public.projects for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists projects_delete on public.projects;
create policy projects_delete on public.projects for delete to authenticated
  using ((select auth.uid()) = user_id);

-- ---- runs
drop policy if exists runs_select on public.runs;
create policy runs_select on public.runs for select to authenticated
  using ((select auth.uid()) = user_id);
drop policy if exists runs_insert on public.runs;
create policy runs_insert on public.runs for insert to authenticated
  with check ((select auth.uid()) = user_id);
drop policy if exists runs_update on public.runs;
create policy runs_update on public.runs for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists runs_delete on public.runs;
create policy runs_delete on public.runs for delete to authenticated
  using ((select auth.uid()) = user_id);

-- ---- run_defects: scoped through the parent run
drop policy if exists run_defects_select on public.run_defects;
create policy run_defects_select on public.run_defects for select to authenticated
  using (run_id in (select id from public.runs where user_id = (select auth.uid())));
drop policy if exists run_defects_insert on public.run_defects;
create policy run_defects_insert on public.run_defects for insert to authenticated
  with check (run_id in (select id from public.runs where user_id = (select auth.uid())));
drop policy if exists run_defects_update on public.run_defects;
create policy run_defects_update on public.run_defects for update to authenticated
  using (run_id in (select id from public.runs where user_id = (select auth.uid())))
  with check (run_id in (select id from public.runs where user_id = (select auth.uid())));
drop policy if exists run_defects_delete on public.run_defects;
create policy run_defects_delete on public.run_defects for delete to authenticated
  using (run_id in (select id from public.runs where user_id = (select auth.uid())));


-- =====================================================================
-- 7. GRANTS
-- =====================================================================
-- Supabase grants broadly to anon/authenticated by default. Nothing here is
-- public, so anon is revoked explicitly rather than left to RLS alone.

revoke all on public.user_settings, public.machines, public.materials,
               public.projects, public.runs, public.run_defects,
               public.run_cost_breakdown
  from anon;

grant select, insert, update, delete on
  public.user_settings, public.machines, public.materials,
  public.projects, public.runs, public.run_defects
  to authenticated;

grant usage, select on sequence public.run_defects_id_seq to authenticated;

grant select on public.domains, public.parameter_defs, public.defect_types,
                public.run_cost_breakdown
  to authenticated;

revoke insert, update, delete on public.domains, public.parameter_defs, public.defect_types
  from authenticated;


-- =====================================================================
-- 8. FDM SEED DATA
-- =====================================================================
-- Phase 1 seeds FDM only. Phase 5 adds CNC / resin / laser as more rows
-- exactly like these, with no schema change.

insert into public.domains (id, display_name, description, unit_label, sort_order) values
  ('fdm', 'FDM 3D Printing', 'Fused deposition modelling: filament extrusion', 'g', 10)
on conflict (id) do update
  set display_name = excluded.display_name,
      description  = excluded.description,
      unit_label   = excluded.unit_label,
      sort_order   = excluded.sort_order;


-- ---- FDM parameters -------------------------------------------------
insert into public.parameter_defs
  (domain_id, key, display_name, group_name, data_type, unit,
   min_value, max_value, step, enum_options, is_required, is_calibration_relevant, help_text, sort_order)
values
  ('fdm','nozzle_temp',          'Nozzle temperature',  'Temperature','number', 'C',    150, 350, 1,    null, true,  true,  'Hot-end temperature for the bulk of the print.', 10),
  ('fdm','first_layer_temp',     'First layer temp',    'Temperature','number', 'C',    150, 350, 1,    null, false, true,  'Often 5-10C above the bulk temperature for adhesion.', 20),
  ('fdm','bed_temp',             'Bed temperature',     'Temperature','number', 'C',    0,   140, 1,    null, false, true,  null, 30),
  ('fdm','chamber_temp',         'Chamber temperature', 'Temperature','number', 'C',    0,   120, 1,    null, false, true,  'Leave blank on open-frame machines.', 40),

  ('fdm','layer_height',         'Layer height',        'Quality',    'number', 'mm',   0.02, 1.2, 0.01, null, true,  true,  null, 50),
  ('fdm','first_layer_height',   'First layer height',  'Quality',    'number', 'mm',   0.05, 1.2, 0.01, null, false, true,  null, 60),
  ('fdm','line_width',           'Line width',          'Quality',    'number', 'mm',   0.1,  2.0, 0.01, null, false, true,  null, 70),
  ('fdm','nozzle_diameter',      'Nozzle diameter',     'Quality',    'number', 'mm',   0.1,  2.0, 0.05, null, false, false, null, 80),

  ('fdm','print_speed',          'Print speed',         'Speed',      'number', 'mm/s', 1,   1000, 1,    null, false, true,  'Outer-wall or average speed, whichever your slicer reports.', 90),
  ('fdm','first_layer_speed',    'First layer speed',   'Speed',      'number', 'mm/s', 1,   500,  1,    null, false, true,  null, 100),
  ('fdm','travel_speed',         'Travel speed',        'Speed',      'number', 'mm/s', 1,   1000, 1,    null, false, false, null, 110),
  ('fdm','acceleration',         'Acceleration',        'Speed',      'number', 'mm/s2',1,   50000,50,   null, false, true,  'Ringing and ghosting track this closely.', 120),

  ('fdm','flow_rate',            'Flow rate',           'Extrusion',  'number', '%',    50,  200,  0.5,  null, false, true,  'Extrusion multiplier as a percentage.', 130),
  ('fdm','retraction_distance',  'Retraction distance', 'Extrusion',  'number', 'mm',   0,   20,   0.1,  null, false, true,  'The first thing to change when you see stringing.', 140),
  ('fdm','retraction_speed',     'Retraction speed',    'Extrusion',  'number', 'mm/s', 1,   200,  1,    null, false, true,  null, 150),
  ('fdm','z_offset',             'Z offset',            'Extrusion',  'number', 'mm',   -2,  2,    0.005,null, false, true,  'Negative squashes the first layer into the bed.', 160),

  ('fdm','infill_percent',       'Infill',              'Structure',  'number', '%',    0,   100,  1,    null, false, false, null, 170),
  ('fdm','infill_pattern',       'Infill pattern',      'Structure',  'enum',   null,   null,null, null,
     array['grid','gyroid','cubic','triangles','lightning','honeycomb','concentric','rectilinear'], false, false, null, 180),
  ('fdm','wall_count',           'Wall count',          'Structure',  'integer',null,   0,   20,   1,    null, false, false, null, 190),
  ('fdm','top_bottom_layers',    'Top/bottom layers',   'Structure',  'integer',null,   0,   20,   1,    null, false, false, null, 200),

  ('fdm','cooling_fan_percent',  'Part cooling fan',    'Cooling',    'number', '%',    0,   100,  1,    null, false, true,  null, 210),

  ('fdm','bed_adhesion',         'Bed adhesion',        'Adhesion',   'enum',   null,   null,null, null,
     array['none','skirt','brim','raft'], false, true, null, 220),
  ('fdm','supports',             'Supports used',       'Adhesion',   'boolean',null,   null,null, null, null, false, false, null, 230),
  ('fdm','surface_prep',         'Bed surface prep',    'Adhesion',   'enum',   null,   null,null, null,
     array['none','glue_stick','hairspray','isopropyl_clean','pei_textured','pei_smooth','tape','glass'], false, true,
     'Cheap to log, and it explains more first-layer failures than temperature does.', 240),

  ('fdm','filament_dried',       'Filament dried',      'Material',   'boolean',null,   null,null, null, null, false, true,
     'Wet filament mimics a dozen other defects. Log it or you will chase ghosts.', 250)
on conflict (domain_id, key) do update
  set display_name            = excluded.display_name,
      group_name              = excluded.group_name,
      data_type               = excluded.data_type,
      unit                    = excluded.unit,
      min_value               = excluded.min_value,
      max_value               = excluded.max_value,
      step                    = excluded.step,
      enum_options            = excluded.enum_options,
      is_required             = excluded.is_required,
      is_calibration_relevant = excluded.is_calibration_relevant,
      help_text               = excluded.help_text,
      sort_order              = excluded.sort_order;


-- ---- FDM defects ----------------------------------------------------
insert into public.defect_types
  (domain_id, key, display_name, description, likely_causes, is_process_related, sort_order)
values
  ('fdm','stringing',              'Stringing / oozing',        'Fine strands between separate features.',
     array['retraction_distance','retraction_speed','nozzle_temp','travel_speed','filament_dried'], true, 10),
  ('fdm','warping',                'Warping / curling',         'Corners lift off the bed or layers curl upward.',
     array['bed_temp','chamber_temp','cooling_fan_percent','bed_adhesion'], true, 20),
  ('fdm','first_layer_adhesion',   'First layer will not stick','Print detaches or the first layer is patchy.',
     array['z_offset','bed_temp','first_layer_temp','first_layer_speed','surface_prep','bed_adhesion'], true, 30),
  ('fdm','elephant_foot',          'Elephant foot',             'First layers bulge outward at the base.',
     array['z_offset','bed_temp','first_layer_temp'], true, 40),
  ('fdm','under_extrusion',        'Under-extrusion',           'Gaps between lines, thin or missing walls.',
     array['flow_rate','nozzle_temp','print_speed','line_width','filament_dried'], true, 50),
  ('fdm','over_extrusion',         'Over-extrusion',            'Blobby walls, rough top surfaces, dimensional bloat.',
     array['flow_rate','nozzle_temp','line_width'], true, 60),
  ('fdm','layer_separation',       'Layer separation',          'Layers split apart under light load.',
     array['nozzle_temp','chamber_temp','cooling_fan_percent','layer_height','filament_dried'], true, 70),
  ('fdm','layer_shift',            'Layer shift',               'The print steps sideways partway up.',
     array['print_speed','acceleration','travel_speed'], true, 80),
  ('fdm','spaghetti',              'Spaghetti failure',         'The part came loose and the printer kept extruding.',
     array['bed_adhesion','surface_prep','z_offset','supports'], true, 90),
  ('fdm','ringing',                'Ringing / ghosting',        'Echoes of sharp features repeating across a surface.',
     array['acceleration','print_speed'], true, 100),
  ('fdm','z_banding',              'Z banding',                 'Regular horizontal bands at a fixed interval.',
     array['layer_height','flow_rate'], true, 110),
  ('fdm','blobs_zits',             'Blobs and zits',            'Small bumps where the nozzle starts or stops a loop.',
     array['retraction_distance','retraction_speed','flow_rate','nozzle_temp'], true, 120),
  ('fdm','pillowing',              'Top surface pillowing',     'Holes or bubbles in the top solid layers.',
     array['top_bottom_layers','cooling_fan_percent','infill_percent'], true, 130),
  ('fdm','support_failure',        'Supports failed',           'Supports collapsed or fused to the part.',
     array['supports','cooling_fan_percent','print_speed'], true, 140),
  ('fdm','dimensional_inaccuracy', 'Dimensional inaccuracy',    'Part measures off-spec in X, Y or Z.',
     array['flow_rate','line_width','nozzle_temp','z_offset'], true, 150),
  ('fdm','nozzle_clog',            'Nozzle clog / heat creep',  'Extrusion stopped mid-print.',
     array['nozzle_temp','print_speed','filament_dried'], true, 160),
  ('fdm','filament_runout',        'Filament ran out',          'The spool emptied mid-print.',
     array[]::text[], false, 900),
  ('fdm','power_loss',             'Power or connection lost',  'Power cut, host disconnect or crashed print server.',
     array[]::text[], false, 910),
  ('fdm','user_cancelled',         'Cancelled on purpose',      'Stopped by choice, not by a fault.',
     array[]::text[], false, 920),
  ('fdm','mechanical_fault',       'Mechanical or hardware fault','Broken part, loose belt, thermistor fault.',
     array[]::text[], false, 930)
on conflict (domain_id, key) do update
  set display_name       = excluded.display_name,
      description        = excluded.description,
      likely_causes      = excluded.likely_causes,
      is_process_related = excluded.is_process_related,
      sort_order         = excluded.sort_order;


-- =====================================================================
-- Done. Verify with:
--   select id, display_name from public.domains;
--   select count(*) from public.parameter_defs where domain_id = 'fdm';   -- expect 25
--   select count(*) from public.defect_types   where domain_id = 'fdm';   -- expect 20
--   select relname, relrowsecurity from pg_class
--     where relnamespace = 'public'::regnamespace and relkind = 'r' order by 1;
--   select c.relname, c.reloptions from pg_class c
--     where c.relname = 'run_cost_breakdown';   -- expect {security_invoker=true}
-- =====================================================================
